Refactor/pep
PerformanceEstimation/PEPit pull request #37
Opened 2022-02-22 17:14 UTC by bgoujaud

L ensemble des changements est décrit en messages de commits:
Tout est fait dans PEP.
Le reste concerne l utilisation des changements.
J ai vérifié:
- les tests
- les examples
- la doc
- le readme
- le notebook
- le papier

Mais si vous voulez verifier que je n ai rien n oublié, c est cool! ;)

2022-02-22 18:17 UTC, AdrienTaylor requested changes
+ error in the test (I don't get it):
==============================================================
>> python -m unittest
(PEPit) Setting up the problem: size of the main PSD matrix: 4x4
(PEPit) Setting up the problem: performance measure is minimum of 1 element(s)
(PEPit) Setting up the problem: initial conditions (2 constraint(s) added)
(PEPit) Setting up the problem: interpolation conditions for 1 function(s)
		 function 1 : 6 constraint(s) added
(PEPit) Compiling SDP
(PEPit) Calling SDP solver
(PEPit) Solver status: optimal (solver: MOSEK); optimal value: -6.331018474007843e-14
(PEPit) Postprocessing: solver's output is not entirely feasible (smallest eigenvalue of the Gram matrix is: -6.88e-14 < 0).
 Small deviation from 0 may simply be due to numerical error. Big ones should be deeply investigated.
 In any case, from now the provided values of parameters are based on the projection of the Gram matrix onto the cone of symmetric semi-definite matrix.
F..............................................................................................
======================================================================
FAIL: test_counter (tests.test_constraints.TestConstraints)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adrien/Github/PEPit/PEPit/tests/test_constraints.py", line 67, in test_counter
    self.assertIs(self.problem.list_of_constraints[i].counter, i)
AssertionError: 8 is not 0

----------------------------------------------------------------------
Ran 95 tests in 15.711s

FAILED (failures=1)
======================================================================
>>python -m unittest tests.test_constraints
.....
----------------------------------------------------------------------
Ran 5 tests in 0.152s

OK

2022-02-22 18:17 UTC, AdrienTaylor commented on PEPit/pep.py
> +            dimension_reduction (bool): Minimize the dimension of the solution (rank of the Gram matrix).
Activate heuristics for minimizing the dimension of the solution.

2022-02-22 18:38 UTC, AdrienTaylor requested changes

2022-02-22 18:38 UTC, AdrienTaylor commented on PEPit/pep.py
> +            dimension_reduction_heuristic (str, optional): The heuristic to be minimized to reduce the dimension.
An heuristic to reduce the dimension

2022-02-23 09:08 UTC, AdrienTaylor approved these changes

2022-02-23 10:26 UTC, M-Celine commented
> * error in the test (I don't get it):
>   ==============================================================
> 
> > > python -m unittest
> > > (PEPit) Setting up the problem: size of the main PSD matrix: 4x4
> > > (PEPit) Setting up the problem: performance measure is minimum of 1 element(s)
> > > (PEPit) Setting up the problem: initial conditions (2 constraint(s) added)
> > > (PEPit) Setting up the problem: interpolation conditions for 1 function(s)
> > > function 1 : 6 constraint(s) added
> > > (PEPit) Compiling SDP
> > > (PEPit) Calling SDP solver
> > > (PEPit) Solver status: optimal (solver: MOSEK); optimal value: -6.331018474007843e-14
> > > (PEPit) Postprocessing: solver's output is not entirely feasible (smallest eigenvalue of the Gram matrix is: -6.88e-14 < 0).
> > > Small deviation from 0 may simply be due to numerical error. Big ones should be deeply investigated.
> > > In any case, from now the provided values of parameters are based on the projection of the Gram matrix onto the cone of symmetric semi-definite matrix.
> > > F..............................................................................................
> > > ======================================================================
> > > FAIL: test_counter (tests.test_constraints.TestConstraints)
> 
> Traceback (most recent call last): File "/home/adrien/Github/PEPit/PEPit/tests/test_constraints.py", line 67, in test_counter self.assertIs(self.problem.list_of_constraints[i].counter, i) AssertionError: 8 is not 0
> 
> Ran 95 tests in 15.711s
> 
> # FAILED (failures=1)
> > > python -m unittest tests.test_constraints
> > > .....
> 
> Ran 5 tests in 0.152s
> 
> OK

I don't have this problem

2022-02-23 10:31 UTC, M-Celine approved these changes
Ok for me, thanks! 
I have with some remarks/questions : 
* You modified set_initial_condition in pep.py to call add_constraints, and then suppress all the call to this function in the examples. Do we really need to keep it then?
* Do we really need two arguments for dimension reduction (dimension_reduction and dimension_reduction_heuristic)?
* In the QuickStart, add dimension_reduction_heuristic="trace" when calling problem.solve(dimension_reduction=True).

2022-02-23 15:23 UTC, merged