Feature/rsi eb
PerformanceEstimation/PEPit pull request #42
Opened 2022-03-04 14:22 UTC by bgoujaud

2022-03-10 15:47 UTC, AdrienTaylor requested changes
- minor comment: short note should be updated/removed
- should discuss names of the files! (previously no function class in the names)

2022-03-10 15:47 UTC, AdrienTaylor commented on PEPit/operators/rsi_eb.py
> +            Lipschitz continuous strongly monotone operators are necessarily continuous,
note is not up to date!

2022-05-13 15:57 UTC, AdrienTaylor commented on PEPit/examples/unconstrained_convex_minimization/subgradient_method_rsi_eb.py
> +    where :math:`f` is :math:`\\mu`-RSI and :math:`L`-EB.
This is nonstandard! Please add appropriate reference(s) for definitions! (and full names of the function classes?)

2022-06-07 23:47 UTC, bgoujaud commented on PEPit/examples/unconstrained_convex_minimization/subgradient_method_rsi_eb.py
> +    where :math:`f` is :math:`\\mu`-RSI and :math:`L`-EB.
I changed name of function and rtd but let RSI EB in the text to shorten it.

2022-06-08 08:24 UTC, AdrienTaylor reviewed
Deux petits commentaires (noms complets pour premières occurences); tu peux changer et merger sans autre round une fois que c'est modif :-)

Par contre, je vois qu'il y a des traces du logdet dans cette version; ça risque pas de poser de problème lors du merge?

2022-06-08 08:24 UTC, AdrienTaylor commented on PEPit/examples/unconstrained_convex_minimization/subgradient_method_rsi_eb.py
> +    where :math:`f` is :math:`\\mu`-RSI and :math:`L`-EB.
I think I would at least put the full name in the first line of the text!  (and shorten it between brackets after the first occurence!)

2022-06-08 08:24 UTC, AdrienTaylor commented on PEPit/functions/rsi_eb.py
> +    for the class of RSI and EB functions.
ici aussi: première occurence -> nom complet?

2022-06-10 00:37 UTC, merged